development:
   adapter: mysql2
   database: demo_app1_development
   username: root
   password:
   host: localhost
  
test:
   adapter: mysql2
   database: demo_app1_test
   username: root
   password:
   host: localhost
   
production:
   adapter: mysql2
   database: demo_app1_production
   username: root
   password:
   host: localhost